// Offline translation dictionaries (Italian -> English, Spanish -> English).
// The dictionary data ships as base64(gzip(keys + values)) generated by
// scripts/build-dicts.mjs. We inflate once per language and serve lookups
// with binary search over the sorted key list — the on-disk bundle stays
// small, and a lookup is just ~20 string comparisons.

import { ungzip } from 'pako';

const cache = new Map();

// common inflection suffixes, tried longest-first as a fallback when the
// surface form is not a headword in the dictionary. The dictionaries already
// contain most inflected forms, so this is only a safety net.
const STEMS = {
  es: ['ándose','iendo','iendo','ando','ando','iendo','ieron','aron','eran','ando','iendo','aría','ado','ido','aba','ado','ido','iendo','ías','os','as','es','a','e','o','s'],
  it: ['erebbe','irebbe','ando','endo','iamo','ate','ata','ato','uto','ito','ono','ano','are','ere','ire','ando','endo','ere','ire','ato','ata','ito','ita','uto','uta','ere','ono','ano','aro','o','a','e','i'],
};

export async function loadDict(lang) {
  if (cache.has(lang)) return cache.get(lang);
  const mod =
    lang === 'es' ? await import('../dict/es-en.js') : await import('../dict/it-en.js');
  const b64 = mod.default;
  const bin = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  const text = new TextDecoder('utf-8').decode(ungzip(bin));
  const sep = text.indexOf('\u0002');
  const keys = text.slice(0, sep).split('\u0000');
  const values = text.slice(sep + 1).split('\u0001');
  if (values.length !== keys.length) {
    throw new Error('dictionary corrupt: key/value count mismatch');
  }
  const dict = { lang, keys, values, size: keys.length };
  dict.lookup = (word) => translate(dict, word);
  cache.set(lang, dict);
  return dict;
}

function bsearch(keys, word) {
  let lo = 0,
    hi = keys.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (keys[mid] < word) lo = mid + 1;
    else if (keys[mid] > word) hi = mid - 1;
    else return mid;
  }
  return -1;
}

function exact(dict, word) {
  const i = bsearch(dict.keys, word);
  return i >= 0 ? dict.values[i] : null;
}

function stripDiacritics(s) {
  return s.normalize('NFD').replace(/\p{M}+/gu, '');
}

/**
 * Translate a foreign-language word to English.
 * Returns { gloss, stem } — stem is the form actually found, if different
 * from the input (useful to show "camminando ← camminare").
 */
export function translate(dict, raw) {
  if (!dict) return null;
  const w = raw.toLowerCase().replace(/[’‘`]/g, "'");
  const norm = stripDiacritics(w);

  // 1. exact surface form (dictionary includes inflected headwords)
  for (const cand of [w, norm]) {
    const g = exact(dict, cand);
    if (g) return { gloss: g, stem: cand === w ? null : cand };
  }
  // 2. strip common inflection suffixes
  for (const suf of STEMS[dict.lang] || []) {
    if (w.length <= suf.length + 2) continue;
    if (!w.endsWith(suf)) continue;
    const stem = w.slice(0, w.length - suf.length);
    for (const cand of [stem, stripDiacritics(stem)]) {
      const g = exact(dict, cand);
      if (g) return { gloss: g, stem };
    }
  }
  return null;
}

/**
 * Translate a multi-word phrase. Exact key match only — suffix stripping is
 * meaningless for phrases. Tries the normalized phrase, then the
 * diacritic-stripped one (e.g. "a través de" -> "a traves de").
 * Returns { gloss, stem } like translate().
 */
export function translatePhrase(dict, phrase) {
  if (!dict) return null;
  const w = phrase.toLowerCase().replace(/[’‘`]/g, "'");
  for (const cand of [w, stripDiacritics(w)]) {
    const g = exact(dict, cand);
    if (g) return { gloss: g, stem: cand === w ? null : cand };
  }
  return null;
}
