// Builds compact dictionary modules (headword -> English gloss) from
// Wiktionary-derived TSV dictionaries (Vuizur/Wiktionary-Dictionaries,
// source data from en.wiktionary.org, CC-BY-SA 4.0).
//
// TSV format:  headword1|headword2|... \t <i>pos</i><br><ol><li>sense</li>...</ol>
//
// Output: src/dict/<lang>-en.js exporting a base64(gzip(keys \x00-joined +
// \x01 values \x00-joined)) string. The runtime (src/lib/dict.js) inflates it
// once and serves lookups by binary search — storage-efficient, no huge
// object literals in the bundle.
//
// Run:  npm run build-dicts

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import zlib from 'node:zlib';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

// All parts of speech and senses of an entry are kept ("adj: ...; noun: ...")
// so the popup shows every variant of a word. There is no length cap: only
// ~0.4% of entries exceed 300 chars and the extra data is negligible after
// gzip. Overlong glosses are handled at display time (clip + show-more in
// the word popup).

function stripHtml(s) {
  return s
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeKey(s) {
  return s
    .normalize('NFD')
    .replace(/\p{M}+/gu, '')
    .replace(/[’‘`]/g, "'")
    .toLowerCase()
    .trim();
}

// A definition is a sequence of blocks: <i>pos</i><br><ol><li>sense</li>...</ol>
// Returns e.g. "adj: sudden, brusque; rough, careless; noun: shelf".
function buildGloss(defHtml) {
  const cleanSense = (s) => {
    s = stripHtml(s);
    return s && !/^alternative (letter-case )?form of/i.test(s) ? s : null;
  };
  const parts = [];
  const blockRe = /<i>([^<]*)<\/i>\s*(?:<br\s*\/?>)?\s*<ol>([\s\S]*?)<\/ol>/g;
  let m;
  while ((m = blockRe.exec(defHtml)) !== null) {
    const pos = stripHtml(m[1]);
    const senses = [...m[2].matchAll(/<li>([\s\S]*?)<\/li>/g)]
      .map((x) => cleanSense(x[1]))
      .filter(Boolean);
    if (senses.length) parts.push((pos ? pos + ': ' : '') + senses.join('; '));
  }
  if (!parts.length) {
    // fallback: no <i>/<ol> structure — take every <li> verbatim
    const senses = [...defHtml.matchAll(/<li>([\s\S]*?)<\/li>/g)]
      .map((x) => cleanSense(x[1]))
      .filter(Boolean);
    if (!senses.length) return null;
    parts.push(senses.join('; '));
  }
  return parts.join('; ');
}

function build(tsvPath) {
  const map = new Map();
  for (const line of readFileSync(tsvPath, 'utf8').split('\n')) {
    if (!line) continue;
    const tab = line.indexOf('\t');
    if (tab === -1) continue;
    const defHtml = line.slice(tab + 1);

    const gloss = buildGloss(defHtml);
    if (!gloss) continue;

    // keep ALL headwords (incl. inflected forms/alternates) so words in
    // running text resolve without stemming
    for (const raw of line.slice(0, tab).split('|')) {
      const head = raw.trim().toLowerCase();
      if (!head || head.length > 40 || !/[a-zà-ÿ]/.test(head)) continue;
      // if the headword appears on multiple lines, keep the richer (longer)
      // gloss so all variants of the word are shown
      if (!map.has(head) || map.get(head).length < gloss.length) {
        map.set(head, gloss);
      }
    }
  }
  // also index accent-stripped forms so diacritic variants resolve
  for (const [head, gloss] of [...map.entries()]) {
    const norm = normalizeKey(head);
    if (norm && norm !== head && !map.has(norm)) map.set(norm, gloss);
  }
  return map;
}

function emit(map, outFile) {
  const keys = [...map.keys()].sort((a, b) => (a < b ? -1 : 1));
  const values = keys.map((k) => map.get(k));
  const keyBuf = Buffer.from(keys.join('\u0000'), 'utf8');
  const valBuf = Buffer.from(values.join('\u0001'), 'utf8');
  const combined = Buffer.concat([keyBuf, Buffer.from('\u0002', 'utf8'), valBuf]);
  const payload = Buffer.from(zlib.gzipSync(combined, { level: 9 })).toString('base64');
  const out =
    `// AUTO-GENERATED by scripts/build-dicts.mjs — do not edit by hand.\n` +
    `// ${map.size} entries. base64( gzip( keys \x00-joined + \x02 + values \x01-joined ) ).\n` +
    `// English glosses derived from Wiktionary (CC-BY-SA 4.0).\n` +
    `export default ${JSON.stringify(payload)};\n`;
  writeFileSync(outFile, out);
  console.log(
    `${outFile}: ${map.size} entries, ${(out.length / 1024 / 1024).toFixed(1)} MB base64`
  );
}

const it = build(path.join(root, 'dicts/it_en.tsv'));
const es = build(path.join(root, 'dicts/es_en.tsv'));
emit(it, path.join(root, 'src/dict/it-en.js'));
emit(es, path.join(root, 'src/dict/es-en.js'));
